### ISSUE TITLE
mpoly over C?

### ISSUE THREAD

**Issue by sommars** [coneill-math/m2r#43]
Is there any way to represent polynomials over C with mpoly? This arose because because polyhedral start systems have coefficients over C, but I'm sure there are other places that we'd want polynomials in C.

**Comment by musicman3320** [comment]
This would aide greatly with coefficient ring support in M2.  More generally than C, what other rings would be possible to support?  Modular arithmetic, for instance?

**Comment by dkahle** [comment]
Sorry, just seeing this. This absolutely can be done, but would require a fairly big overhaul of [__mpoly__](https://github.com/dkahle/mpoly). See [the paper](https://journal.r-project.org/archive/2013-1/kahle.pdf) too, to understand what the actual data structure of an mpoly is.

I short, an `mpoly` object is a list whose elements represent terms.  The elements are named vector that always have an element called `coef` representing the coefficient.  For example, the monomial 2xy^2 would be
```r
list(
  c(x = 1, y = 2, coef = 2)
)
```
The polynomial 2xy^2 + x + 1 would be
list(
  c(x = 1, y = 2, coef = 2),
  c(x = 1, coef = 1),
  c(coef = 1)
)
```
This is a very efficient representation of a multivariate polynomial, but it doesn't make writing algorithms for them easy.

In any case, a better representation of a monomial would be itself a named list with elements `term` (is there a better name here?), which would be a named integer vector, and `coef`, which would be the coefficient, and whose type could be (in principle) anything - a numeric(1), a complex(1), or perhaps even classed objects (e.g. an `mpoly` itself).  Two of the consequences of the current implementation are that (1) the exponents are stored as numerics (doubles) instead of ints, and so are less efficient in terms of space, and more importantly (2) the coefficient also has to be a numeric (double), so in particular it's gotta be real.

I'd like to do that overhaul to __mpoly__, but I don't have time now.  If you'd like to do it and submit a PR, I'd be happy with that. But it'd be one piece of other changes that we'd like to make to __mpoly__ to make it much better.  A similar change would be the whole `mpolyList` thing, which now seems to be a terrible idea.  For example, it doesn't extend to arrays of _mpoly_s.  Another change would be to implement rational functions. I think those three changes would make __mpoly__ significantly better for __m2r__...

**Comment by musicman3320** [comment]
Agreed.  This would likely require some changes on both ends, i.e. in both **mpoly** and **m2r**, with the bulk of the changes happening in the former.  Definitely a project for a rainy day at some point in the future.

**Comment by sommars** [comment]
It could be a good summer activity for the students you're going to be working with.

**Comment by coneill-math** [comment]
Complex numbers now supported in m2r, just need mpoly support.  Closing.
