### ISSUE TITLE
Allow names to be given to m2.() and m2()

### ISSUE THREAD

**Issue by dkahle** [coneill-math/m2r#80]
It would be helpful if we could set the name (`m2_name`) of the return value of a chunk of code, and I think we may need this to enable pointer arguments for certain functions.   For example, 
```r
factor_n(218700)
#      prime power
# [1,]     2     2
# [2,]     3     7
# [3,]     5     2
```
works just fine, but when I try to pass in a pointer to the same number, failure:
```r
factor_n(m2.("218700"))
#  Error in m2.(m2_code) : Macaulay2 Error! 
```
What's happening is that `m2.()` returns standard pointer info, including the name of the thing (e.g. `m2o4`), and that name is what gets used when creating the M2 call (e.g. `factor m2o4`).

Seems to me two solutions might exist.
1. Allow users to pass a name argument (maybe `m2_name`?) to `m2.()` and `m2()` that names the output, so that instead of `m2o#` it receives whatever name is given.  (E.g., `m2.("218700", m2_name = "a")` returns a `m2_pointer` object with `m2_name = "a"`.)
2. Instead of constructing the code with the pointer's `m2_name`, construct it with it's `ext_str` argument.  That seems somewhat dangerous though, since that's not always reproducible, right?

**Comment by dkahle** [comment]
I think the example here is wrong, but the intent may be helpful. Let me get back...

**Comment by musicman3320** [comment]
This would be useful, but might be a pain to implement in every . function. Perhaps we can implement it in `m2.()`?  Alternatively, could we write a general function, intended to be called at the beginning of every . function, that handle some of the general inputs?

**Comment by musicman3320** [comment]
Does this work as expected now?  We currently test nested dot and non-dot calls quite a bit in the test cases.  Though perhaps I am missing something...

**Comment by coneill-math** [comment]
Pretty sure this works as expected now.  Please reopen if I am missing something.
